version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      identity-dependencies:
        patterns:
          - Microsoft.Identity.*
          - Microsoft.IdentityModel.*
          - System.IdentityModel.*

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
